# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 721, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.login = QtWidgets.QWidget()
        self.login.setObjectName("login")
        self.login_input_usuario = QtWidgets.QLineEdit(self.login)
        self.login_input_usuario.setGeometry(QtCore.QRect(200, 70, 113, 20))
        self.login_input_usuario.setObjectName("login_input_usuario")
        self.login_input_senha = QtWidgets.QLineEdit(self.login)
        self.login_input_senha.setGeometry(QtCore.QRect(200, 130, 113, 20))
        self.login_input_senha.setObjectName("login_input_senha")
        self.login_btn_entrar = QtWidgets.QPushButton(self.login)
        self.login_btn_entrar.setGeometry(QtCore.QRect(230, 220, 75, 23))
        self.login_btn_entrar.setObjectName("login_btn_entrar")
        self.login_erro = QtWidgets.QLabel(self.login)
        self.login_erro.setGeometry(QtCore.QRect(220, 180, 47, 13))
        self.login_erro.setText("")
        self.login_erro.setObjectName("login_erro")
        self.tabWidget.addTab(self.login, "")
        self.sistema = QtWidgets.QWidget()
        self.sistema.setEnabled(False)
        self.sistema.setObjectName("sistema")
        self.label = QtWidgets.QLabel(self.sistema)
        self.label.setGeometry(QtCore.QRect(180, 120, 151, 16))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.sistema, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_btn_entrar.setText(_translate("MainWindow", "Entrar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.login), _translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Login realizado com sucesso"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sistema), _translate("MainWindow", "Sistema"))
